apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.group: cntk
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/sealed-secrets
    repoURL: https://github.com/vbudi000/gitops-rosa-east-2.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
