apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  project: services
  source:
    path: 2-services/operators/cert-manager
    repoURL: https://github.com/vbudi000/gitops-rosa-east-2.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
