global: {}
refarch-machinesets:
  infrastructureId: "rosa-east-2-zv89m"
  cloudProvider: "aws"
  aws:
    region: us-east-1
    zones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    image: ami-01ea0772949cb189a
    infraNodes:
      nodeCount: 1
      volumeSize: 120
      volumeType: gp2
      instanceType: m5.xlarge
    storageNodes:
      nodeCount: 1
      volumeSize: 120
      volumeType: gp2
      instanceType: m5.4xlarge
    cloudpakNodes:
      nodeCount: 0
      volumeSize: 120
      volumeType: gp2
      instanceType: m5.xlarge
