apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-ci
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/ci
    repoURL: https://github.com/vbudi000/gitops-rosa-east-2.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
